import type {NextPage} from 'next'
import Head from 'next/head'
import Header from '../Components/Header'
import Footer from '../Components/Footer'
import StripeBackground from '../Components/StripeBackground'
import HomePage from '../Components/HomePage'
import {useEffect, useState} from 'react'
import {getBrowserType, browserVersion, isMacOS} from '../helpers'

const Home: NextPage = () => {
  const [isLoaded, setIsLoaded] = useState(false)

  useEffect(() => {
    if (typeof window !== 'undefined') {
      const $body: HTMLBodyElement | null = document.querySelector('body')
      if (!$body) return
      // get classes
      let classes = $body.className.split(' ').filter(cls => !!cls)
      // ie
      if (getBrowserType() === 'ie') {
        const ver = browserVersion('ie')
        classes.push(`ie${ver}`)
      }
      // mac
      if (isMacOS() && !classes.includes('is-mac')) {
        classes.push('is-mac')
      }
      $body.className = classes.join(' ')
    }
  }, [])

  const onSourceLoaded = () => {
    setIsLoaded(true)
  }

  return (
    <div className={['xm-home-page', isLoaded ? 'start' : ''].join(' ')}>
      <StripeBackground/>
      <Head>
        <title>Home - Capricorncd</title>
        <meta name="description" content="Generated by create next app, https://github.com/capricorncd"/>
        <link rel="icon" href="/favicon.png"/>
      </Head>

      <Header/>
      <HomePage onLoaded={onSourceLoaded}/>
      <Footer/>
    </div>
  )
}

export default Home
