/**
 * Created by Capricorncd.
 * https://github.com/capricorncd
 * Date: 2021-03-07 11:26
 */
import '../../static/FlashVHtml/css/normalize.css'
import '../../static/FlashVHtml/css/main.css'
import '../../static/FlashVHtml/tweening/TweenLite.min.js'
import '../../static/FlashVHtml/tweening/EasePack.min.js'
import '../../static/FlashVHtml/tweening/CSSPlugin.min.js'
import '../../static/FlashVHtml/stats.min.js'
import '../../static/FlashVHtml/Math2.js'
import '../../static/FlashVHtml/pixi/utils/Utils.js'
import '../../static/FlashVHtml/pixi/utils/EventTarget.js'
import '../../static/FlashVHtml/pixi/utils/gl-matrix-min.js'
import '../../static/FlashVHtml/pixi/renderers/WebGLShaders.js'
import '../../static/FlashVHtml/pixi/renderers/WebGLRenderer.js'
import '../../static/FlashVHtml/pixi/renderers/CanvasRenderer.js'
import '../../static/FlashVHtml/pixi/renderers/DOMRenderer.js'
import '../../static/FlashVHtml/pixi/Point.js'
import '../../static/FlashVHtml/pixi/DisplayObject.js'
import '../../static/FlashVHtml/pixi/renderers/WebGLBatch.js'
import '../../static/FlashVHtml/pixi/DisplayObjectContainer.js'
import '../../static/FlashVHtml/pixi/Stage.js'
import '../../static/FlashVHtml/pixi/Sprite.js'
import '../../static/FlashVHtml/pixi/extras/Strip.js'
import '../../static/FlashVHtml/pixi/MovieClip.js'
import '../../static/FlashVHtml/pixi/textures/BaseTexture.js'
import '../../static/FlashVHtml/pixi/textures/Texture.js'
import '../../static/FlashVHtml/pixi/utils/Detector.js'
import '../../static/FlashVHtml/pixi/loaders/SpriteSheetLoader.js'
import '../../static/FlashVHtml/pixi/loaders/AssetLoader.js'
import '../../static/FlashVHtml/leap.min.js'
import '../../static/FlashVHtml/pixi/extras/Rope.js'
import '../../static/FlashVHtml/Tentacle.js'
import '../../static/FlashVHtml/Invaders.js'
import '../../static/FlashVHtml/WasteInvaders.js'
